# Rime default settings
# encoding: utf-8

config_version: '0.40'

# 方案列表
schema_list:
  - schema: 092wb
#  - schema: py

switcher:
  caption: 〔方案选单〕
  hotkeys:
    - Control+Shift+grave

  fold_options: true  # 呼出时是否折叠，多方案时建议折叠 true ，一个方案建议展开 false
  abbreviate_options: true      # 折叠时是否缩写选项
  option_list_separator: ' / '  # 折叠时的选项分隔符

# 菜单
menu:
  page_size: 10  # 候选词个数
  # alternative_select_labels: [ ①, ②, ③, ④, ⑤, ⑥, ⑦, ⑧, ⑨, ⑩ ]  # 修改候选项标签
  # alternative_select_keys: ASDFGHJKL  # 如编码字符占用数字键，则需另设选字键

# 符号
punctuator:
  full_shape:
    __include: punctuation:/full_shape
  half_shape:
    __include: punctuation:/half_shape

# 快捷键
key_binder:
  bindings:
    __patch:
      - 092wb_key_bindings:/092wb_hotkeys

recognizer:
  patterns:
    punct: "^zi([0-9]0?|[A-Za-z]+)$"          # 特殊符号引导规则
    reverse_lookup: "^z[a-z]*'?$"             # 反查规则
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"
    helper: '^aid$'
    unicode: "^U[a-f0-9]+"              # lua_translator@unicode，输出 Unicode 字符
    number: "^R[0-9]+[.]?[0-9]*"        # lua_translator@number_translator，数字金额大写
    gregorian_to_lunar: "^N[0-9]{1,8}"  # lua_translator@lunar，公历转农历，输入 N20240115 得到「二〇二三年腊月初五」

# 功能键行为
ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Shift_L: commit_text
    Shift_R: commit_text
    Control_L: noop
    Control_R: noop
    Caps_Lock: clear
    Eisu_toggle: clear
