# Rime default settings
# encoding: utf-8

config_version: '0.40'

schema_list:
  - schema: 092wb

switcher:
  caption: 〔方案选单〕
  hotkeys:
    - Control+Shift+grave

  fold_options: true

ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Shift_L: commit_text
    Shift_R: commit_text
    Control_L: noop
    Control_R: noop
    Caps_Lock: clear
    Eisu_toggle: clear
